export const perfumes = [
  {
    _id: "1",
    name: "Aroma Blossom",
    image: "/images/perfumes/perfume1.jpg",
    description: "A floral fragrance with notes of jasmine and rose.",
    brand: "Aroma Sphere",
    category: "Floral",
    price: 50.99,
    countInStock: 25,
    rating: 3.7,
    numberOfReviews: 120,
  },
  {
    _id: "2",
    name: "Citrus Dream",
    image: "/images/perfumes/perfume2.jpg",
    description: "A refreshing citrus blend with lemon and orange zest.",
    brand: "Aroma Sphere",
    category: "Citrus",
    price: 45.99,
    countInStock: 30,
    rating: 4.5,
    numberOfReviews: 85,
  },
  {
    _id: "3",
    name: "Woodland Essence",
    image: "/images/perfumes/perfume3.jpg",
    description: "A woody fragrance with hints of sandalwood and cedar.",
    brand: "Aroma Sphere",
    category: "Woody",
    price: 60.0,
    countInStock: 15,
    rating: 3.8,
    numberOfReviews: 200,
  },
  {
    _id: "4",
    name: "Lavender Breeze",
    image: "/images/perfumes/perfume4.jpg",
    description: "A calming lavender fragrance with a hint of vanilla.",
    brand: "Aroma Sphere",
    category: "Floral",
    price: 55.5,
    countInStock: 50,
    rating: 4.6,
    numberOfReviews: 150,
  },
  {
    _id: "5",
    name: "Midnight Oud",
    image: "/images/perfumes/perfume5.jpg",
    description: "A deep and mysterious oud fragrance with hints of amber.",
    brand: "Aroma Sphere",
    category: "Oud",
    price: 85.99,
    countInStock: 10,
    rating: 4.9,
    numberOfReviews: 75,
  },
  {
    _id: "6",
    name: "Tropical Paradise",
    image: "/images/perfumes/perfume6.jpg",
    description: "A tropical blend with pineapple, coconut, and passion fruit.",
    brand: "Aroma Sphere",
    category: "Fruity",
    price: 48.75,
    countInStock: 20,
    rating: 4.4,
    numberOfReviews: 110,
  },
  {
    _id: "7",
    name: "Eternal Rose",
    image: "/images/perfumes/perfume7.jpg",
    description: "A luxurious rose fragrance with a touch of vanilla and musk.",
    brand: "Aroma Sphere",
    category: "Floral",
    price: 72.0,
    countInStock: 5,
    rating: 5,
    numberOfReviews: 90,
  },
  {
    _id: "8",
    name: "Spiced Amber",
    image: "/images/perfumes/perfume8.jpg",
    description: "A warm and spicy fragrance with amber, cinnamon, and clove.",
    brand: "Aroma Sphere",
    category: "Spicy",
    price: 68.99,
    countInStock: 12,
    rating: 4.7,
    numberOfReviews: 65,
  },
  {
    _id: "9",
    name: "Ocean Breeze",
    image: "/images/perfumes/perfume9.jpg",
    description:
      "A fresh oceanic fragrance with a hint of sea breeze and citrus.",
    brand: "Aroma Sphere",
    category: "Fresh",
    price: 42.99,
    countInStock: 40,
    rating: 4.3,
    numberOfReviews: 100,
  },
  {
    _id: "10",
    name: "Vanilla Dream",
    image: "/images/perfumes/perfume10.jpg",
    description: "A sweet and comforting vanilla fragrance with caramel notes.",
    brand: "Aroma Sphere",
    category: "Sweet",
    price: 49.5,
    countInStock: 30,
    rating: 4.6,
    numberOfReviews: 130,
  },
];
